/**
 * BloxdCode Generator - Core Engine
 * 今後HTML側に設定項目（inputタグやcheckbox）を増やしても、
 * このJSの「CONFIG」を少し書き換えるだけで自動的に対応できる拡張性の高い設計です。
 */

// 1. ジェネレーターの設定データ（ここで生成するコードのルールを定義します）
const BLOXD_CONFIG = {
    // クライアントオプション（プレイヤーの能力や環境設定）
    clientOptions: [
        { id: 'airJumpCount', key: 'airJumpCount', type: 'number', default: 0 }, // 空中ジャンプ回数 [cite: 14]
        { id: 'maxHealth', key: 'maxHealth', type: 'number', default: 100 },     // 最大体力 [cite: 61]
        { id: 'speedMultiplier', key: 'speedMultiplier', type: 'number', default: 1 }, // 移動速度 [cite: 81]
        { id: 'jumpAmount', key: 'jumpAmount', type: 'number', default: 8 },     // ジャンプ力 [cite: 59]
        { id: 'invincible', key: 'invincible', type: 'boolean', default: false },// 無敵化 [cite: 59]
        { id: 'fallDamage', key: 'fallDamage', type: 'boolean', default: false },// 落下ダメージ [cite: 43]
        { id: 'canCraft', key: 'canCraft', type: 'boolean', default: true },     // クラフト許可 [cite: 26]
        { id: 'canChange', key: 'canChange', type: 'boolean', default: true }    // ブロック変更許可 [cite: 26]
    ],
    
    // イベントコールバック（特定のアクションが起きたときの処理）
    callbacks: {
        joinMessage: { id: 'cb_joinMessage', name: 'onPlayerJoin' },
        chatPrefix: { id: 'cb_chatPrefix', name: 'onPlayerChat' },
        blockStandLog: { id: 'cb_blockStandLog', name: 'onBlockStand' }
    }
};

// 2. HTMLの入力値を取得するヘルパー関数
function getInputValue(id, type, defaultValue) {
    const el = document.getElementById(id);
    if (!el) return defaultValue; // HTMLに要素がない場合はデフォルト値を返す
    
    if (type === 'number') {
        const val = parseFloat(el.value);
        return isNaN(val) ? defaultValue : val;
    } else if (type === 'boolean') {
        return el.checked;
    } else if (type === 'string') {
        return el.value || defaultValue;
    }
    return defaultValue;
}

// 3. メインのコード生成関数（ボタンを押した時に実行）
function generateBloxdCode() {
    let generatedCode = `// --- Bloxd.io Custom World Code ---\n`;
    generatedCode += `// Generated by BloxdCode Maker\n\n`;

    // --- クライアントオプションの生成 ---
    // HTMLの入力状態を読み取り、デフォルト値と違うものだけを抽出する
    const optionsToSet = {};
    BLOXD_CONFIG.clientOptions.forEach(opt => {
        const val = getInputValue(opt.id, opt.type, opt.default);
        // デフォルト値から変更されている場合のみコードに追加する（コードを綺麗に保つため）
        if (val !== opt.default) {
            optionsToSet[opt.key] = val;
        }
    });

    // --- onPlayerJoin (プレイヤー参加時の処理) [cite: 162] ---
    generatedCode += `onPlayerJoin = (playerId) => {\n`;
    
    // 変更されたクライアントオプションがあれば、一括で適用するコードを生成 
    if (Object.keys(optionsToSet).length > 0) {
        generatedCode += `    // プレイヤー設定を適用\n`;
        generatedCode += `    api.setClientOptions(playerId, {\n`;
        for (const [key, value] of Object.entries(optionsToSet)) {
            const formattedValue = typeof value === 'string' ? `"${value}"` : value;
            generatedCode += `        ${key}: ${formattedValue},\n`;
        }
        generatedCode += `    });\n`;
    }

    // 参加ログのオプションがONなら追加
    if (getInputValue(BLOXD_CONFIG.callbacks.joinMessage.id, 'boolean', false)) {
        generatedCode += `\n    // 参加ログをサーバーに表示\n`;
        generatedCode += `    api.log(playerId + " がワールドに参加しました！");\n`;
    }
    generatedCode += `};\n\n`;

    // --- onPlayerChat (チャット送信時の処理)  ---
    if (getInputValue(BLOXD_CONFIG.callbacks.chatPrefix.id, 'boolean', false)) {
        generatedCode += `onPlayerChat = (playerId, chatMessage, channelName) => {\n`;
        generatedCode += `    // メッセージの先頭に [Player] というプレフィックス（接頭辞）をつける\n`;
        generatedCode += `    return "[[Player]] "; \n`;
        generatedCode += `};\n\n`;
    }

    // --- onBlockStand (ブロックの上に乗った時の処理) [cite: 103, 104] ---
    if (getInputValue(BLOXD_CONFIG.callbacks.blockStandLog.id, 'boolean', false)) {
        generatedCode += `onBlockStand = (playerId, x, y, z, blockName) => {\n`;
        generatedCode += `    // 金ブロックに乗った時だけ特殊な処理をする例\n`;
        generatedCode += `    if (blockName === "Block of Gold") {\n`;
        generatedCode += `        api.applyEffect(playerId, "Speed", 5000); // 5秒間スピードアップ\n`;
        generatedCode += `    }\n`;
        generatedCode += `};\n\n`;
    }

    // --- tick (毎フレームの処理) [cite: 204] ---
    // ゲーム内で20回/秒呼ばれるループ処理の枠だけ用意しておく
    generatedCode += `tick = (ms) => {\n`;
    generatedCode += `    // ここに常に実行し続ける処理を書きます（上級者向け）\n`;
    generatedCode += `};\n`;

    // 4. 結果を画面に出力
    const outputEl = document.getElementById('codeOutput');
    if (outputEl) {
        outputEl.value = generatedCode;
        // 少しアニメーションでハイライトする（UIのちょっとした工夫）
        outputEl.style.backgroundColor = '#1a2b1a';
        setTimeout(() => { outputEl.style.backgroundColor = '#15151c'; }, 300);
    }
}

// 5. コピー機能
function copyToClipboard() {
    const codeOutput = document.getElementById('codeOutput');
    if (!codeOutput || !codeOutput.value) {
        alert("先にコードを生成してください！");
        return;
    }
    
    codeOutput.select();
    document.execCommand('copy');
    alert("コピー完了！Bloxd.ioのワールドコード(F8)に貼り付けてください。");
}
